name: Update Activity Graph

on:
  schedule:
    - cron: "0 4 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate Activity Graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: luismariogp
          options: bg_color=0F172A&color=CBD5E1&line=2563EB&point=60A5FA&area=true&hide_border=true&custom_title=GitHub%20Activity
          output_path: profile/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Activity Graph
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/activity-graph.svg
          git commit -m "Update activity graph" || exit 0
          git push
